### ISSUE TITLE
Cursor column color

### ISSUE THREAD

**Issue by fedeotaran** [jacoborus/tender.vim#10]
When set cursor column looks like this:

![screenshot from 2016-09-02 10-18-04](https://cloud.githubusercontent.com/assets/1789688/18205334/d4f48ba0-70f7-11e6-974b-99171c4f17c7.png)

I missed something?

**Comment by jacoborus** [comment]
This is not a Tender issue, maybe another plugin is changing the colorcolumn color.  https://github.com/jacoborus/tender.vim/blob/4dc56c73beb9ec4c614238c032504babf37ee152/colors/tender.vim#L19

**Comment by fedeotaran** [comment]
This line set highlight to ColorColumn.
link CursorColumn CursurLine work fine?

I disabled all others plugins and the problem persists

**Comment by jacoborus** [comment]
Does this command solve the problem?

``` vim
:hi ColorColumn guifg=NONE ctermfg=NONE guibg=#323232 ctermbg=236 gui=NONE cterm=NONE
```

**Comment by fedeotaran** [comment]
No, but this command solve the problem :)

`
:hi CursorColumn guifg=NONE ctermfg=NONE guibg=#323232 ctermbg=236 gui=NONE cterm=NONE
`

Note CursorColumn instead of ColorColumn

**Comment by jacoborus** [comment]
Ok, now I can reproduce the error, but I don't know why the `hi link` is not working.

**Comment by fedeotaran** [comment]
:+1:  :)
