### ISSUE TITLE
Visual Mode highlighting turned off

### ISSUE THREAD

**Issue by ihgann** [jacoborus/tender.vim#13]
When entering visual mode in vim, visual highlighting no longer occurs.

I'm on OSX, using iTerm2, vim 8.0 (installed via homebrew), and have pulled the latest code.

**Comment by JeffFaer** [comment]
Visual highlighting occurs for me, but it's very faint.

![image](https://cloud.githubusercontent.com/assets/2907401/18534122/2cc8b4f6-7ab6-11e6-8d13-e4abc5a510e0.png)

Ubuntu 16.04, Vim 7.4.1689

**Comment by jacoborus** [comment]
@ihgann @JeffreyFalgout  are you using true colors or 256?

**Comment by hugomd** [comment]
For me it appears completely black:
![](http://d.hugo.sx/ThX5+)

Is there any accompanying iTerm2 theme to go with this Vim theme?

**Comment by jacoborus** [comment]
@hugomd that is how it should appears. iTerm2 theme is on the way, check again in a couple of days please.

An advice: [othree/yajs](https://github.com/othree/yajs.vim) can give you a better javascript syntax highlighting

**Comment by ghost** [comment]
+1

Great theme. Switched from solarized. Looking forward to iTerm2 theme!

**Comment by jacoborus** [comment]
@civiclabsconsulting @hugomd [iTerm2 theme](https://gist.github.com/yads/a69cff702f0283bef2a3fa390650091a)

**Comment by ihgann** [comment]
@JeffreyFalgout Jeffrey, I get this same exact response now. It's super faint.

@jacoborus I love the iTerm2 theme!!

**Comment by hugomd** [comment]
Awesome, thanks @jacoborus - it looks great!

**Comment by ihgann** [comment]
@jacoborus `set termguicolors` fixed the issue for me.

I noticed that this only happened to me in iTerm2, as well. Using regular Terminal.app, this was never an issue.

**Comment by jacoborus** [comment]
nice!
