### ISSUE TITLE
Background washed out.

### ISSUE THREAD

**Issue by pnunn** [jacoborus/tender.vim#15]
When I turn on this color scheme, the whole window gets washed out.  See the attached screen shot of side by side tmux windows. One without vim, the other with vim open 

<img width="648" alt="vim" src="https://cloud.githubusercontent.com/assets/1034315/18550624/16a5ddc4-7b98-11e6-8719-6d1a9bc22d7f.png">

Any ideas how to fix the contrast?

**Comment by hugomd** [comment]
@pnunn Could you post your `.vimrc`?

**Comment by jacoborus** [comment]
@pnunn I'm afraid this is a problem that you will have with any grey background over a transparent terminal. Try this commands in vim and let me know if it solves the problem please:

``` viml
:hi Normal guifg=#eeeeee ctermfg=255 guibg=#000000 ctermbg=0 gui=NONE cterm=NONE
:hi Visual guifg=NONE ctermfg=NONE guibg=#282828 ctermbg=235 gui=NONE cterm=NONE
```

**Comment by pnunn** [comment]
Thanks guys. @jacoborus these actually made the situation worse. You are correct in that I am using a semi transparent terminal (iterm on mac).

**Comment by pnunn** [comment]
I've been playing around with this. I get the same effect in HyperTerm (which is opaque black background) and en iTerm2 when I turn off the transparency. Just incase I'm doing something wrong, attached is my .vimrc
[vimrc.txt](https://github.com/jacoborus/tender.vim/files/475936/vimrc.txt)
(file name changed so it would upload).

**Comment by jacoborus** [comment]
@pnunn what "Background washed out" means? Can you post a screenshot with a solid background?

**Comment by jacoborus** [comment]
@pnunn your vim colorscheme looks different to my screenshots because you need to enable true colors in your terminal and vim config. Maybe [this comment](https://www.reddit.com/r/vim/comments/52mzr3/tender_a_dark_and_fresh_24bit_colorscheme_for_vim/d7odesy) or [this gist](https://gist.github.com/XVilka/8346728) can help you

**Comment by pnunn** [comment]
I have added the two lines in the comment and it is now closer (screen shot with black, opaque background attached). You can still see the grayness but it is better. 
<img width="1587" alt="vim2" src="https://cloud.githubusercontent.com/assets/1034315/18574169/c22f1f3c-7c0d-11e6-8d46-b71513150ddf.png">

I'll keep digging in the gist and see if I can turn up anything.

**Comment by pnunn** [comment]
OK, have it working like a champ now.. followed this page (without replacing tmux as it was already at 2.2)

https://chris.chowie.net/2015/04/19/True-colour-with-neovim-tmux-and-iterm2/

**Comment by pnunn** [comment]
Nope.. spoke too soon. Wasn't showing up because Vundle wasn't running so neither was tender.vim.

Just got Vundle working and neovim is doing the same thing sigh.

**Comment by jacoborus** [comment]
Ok, let's begin again step by step. 
1. What version of vim are you running? 24bit colorschemes require neovim or vim higher than v7.4.1770 
2. Did you enable true colors in vim/neovim? nvim: `set termguicolors` , vim v7.4.1770 or newer (Vim 8 doesn't need this): `set guicolors`
3. Does vim show the right colors while running alone in a opaque terminal without tmux?

**Comment by pnunn** [comment]
vim, 7.4.889  neovim, 0.1.6-dev
I'm trying to upgrade to vim 8 at the moment.

set termguicolors made no change
set guicolors was invalid option for both vim and neovim
tmux does not seem to have any impact. I get the same thing with tmux, 
no tmux (both on iTerm2) and HyperTerm no tmux.

Peter.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

**Comment by jacoborus** [comment]
I think the problem is in your terminal, try:

``` sh
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

It should look like this:
![selection_074](https://cloud.githubusercontent.com/assets/829859/18584977/8ae4c034-7c14-11e6-92e1-894cca3eddaa.png)

**Comment by pnunn** [comment]
Yep, that's what it looks like both with and without tmux :(

P.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

**Comment by jacoborus** [comment]
I'm running out of ideas... can you try another 24 bit colorscheme and see what happens?

**Comment by pnunn** [comment]
Um.. sure, what would you suggest :) (Don't know a lot about this).
P.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

**Comment by jacoborus** [comment]
Try [badwolf](https://github.com/sjl/badwolf) and compare the result with the screenshots

**Comment by pnunn** [comment]
badwolf does the same thing. Colors seem to be OK, but a slightly grey 
background on the whole of nvim and grey background on each character in 
vim.

Peter.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

**Comment by pnunn** [comment]
Sorry I was wrong, I didn't turn on badwolf, just enabled it, badwolf 
works fine.

P.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

**Comment by jacoborus** [comment]
hey @pnunn , did the upgrade to vim8 go well?

**Comment by pnunn** [comment]
Hi Jacobo,

upgrade to 8 went fine, still problems with the color scheme though. 
Several others are working without the effect I'm seeing from tender 
(the suggested badwolf for example). It is interesting that badwolf has  
the effect on text in the file but I think that's by design. Not on 
every line.

Hope you had a good weekend.

P.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

**Comment by jacoborus** [comment]
Ok, the last try: I made a clean vim8 install and found the same problem you have, after some changes in tender code it worked with this `.vimrc`:

``` viml
set nocompatible
filetype off
set termguicolors
syntax enable
colorscheme tender
```

**Comment by pnunn** [comment]
Lol.. thanks SO much for the efforts Jacobo.  Still no joy. I've payed 
around with these setting and can certainly change the look (some much 
more subtle than others) but I still get the background effect.

Peter.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

**Comment by AlessandroYorba** [comment]
@pnunn 

I've seen this issue before. Try adding this to your .vimrc

``` VimL
" disable Background Color Erase (BCE) so that color schemes
" render properly when inside 256-color tmux and GNU screen.
if &term =~ '256color'
    set t_ut=
endif
```

**Comment by pnunn** [comment]
Thank you Alessandro, that seems to have done it. :)

I'm getting errors with set termguicolors saying its not an available 
option, is that right?

However, colors seem to be good now.

P.

## 

Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707

AlessandroYorba wrote:

> set  termguicolors

**Comment by AlessandroYorba** [comment]
@pnunn In my experience vim will output an Error like that if it doesn't detect termguicolors feature at all. Verify which Vim the terminal is referencing by opening your shell and typing `vim --version`  if termguicolors is supported you should see it printed to the screen in the list of features like so `+termguicolors`

**Comment by jacoborus** [comment]
Thanks @AlessandroYorba
