### ISSUE TITLE
Font colors don't load properly in Gnome-terminal on startup of Vim

### ISSUE THREAD

**Issue by nickcorona** [jacoborus/tender.vim#16]
This is how the fonts look with the tender color scheme set in my ~/.vimrc file: http://storage6.static.itmages.com/i/16/0917/h_1474148828_5849431_cb6363de79.png

This is how the fonts look like after I manually set the color scheme in vim:
http://storage7.static.itmages.com/i/16/0917/h_1474148949_3041085_5f50dc257e.png

What's the issue?

**Comment by jacoborus** [comment]
I can see 2 different problems in your screenshots. The first one looks like something is overwriting the syntax highlighting, try moving `colorscheme tender` to the bottom of your vim config.

The second one shows that your vim installation does not support true colors. You need vim8+ or neovim

**Comment by nickcorona** [comment]
colorscheme tender is at the bottom of my vim configuration. Also, I have vim8+: http://storage2.static.itmages.com/i/16/0918/h_1474214564_8038487_9fa5dcc77a.png

**Comment by jacoborus** [comment]
You need to add this to `.vimrc` in order to enable true colors:

``` viml
set termguicolors
```

I installed vim8 and I can't make vim to load tender from `.vimrc`...

**Comment by jacoborus** [comment]
@nickcorona can you update your installation and tell me if it works now please?

**Comment by nickcorona** [comment]
I'll let you know when I get home.

**Comment by nickcorona** [comment]
I updated my installation of tender. It works now! Whatever you did fixed it. Thanks.

**Comment by jacoborus** [comment]
Thanks to you, I didn't realize that. I just set `background=dark` for all the platforms...
