### ISSUE TITLE
unknown option: guicolors

### ISSUE THREAD

**Issue by getsadzeg** [jacoborus/tender.vim#17]
When I run vim(7.4), it says:

``` vim
Error detected while processing /home/user/.vimrc:
line   17:
E518: Unknown option: guicolors
```

my .vimrc:

``` vim
set nocompatible
set nu

filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'jacoborus/tender'
call vundle#end()
set guicolors
colorscheme tender
filetype plugin indent on
```

**Comment by jacoborus** [comment]
Vim version?

**Comment by getsadzeg** [comment]
Oh, I missed it. Vim version is 7.4

**Comment by jacoborus** [comment]
`set guicolors` is for vim v7.4.1770 or newer in order to enjoy the 24bit version of the colorscheme. Vim 8 doesn't need that config line

**Comment by getsadzeg** [comment]
So? Don't I need that line?

**Comment by jacoborus** [comment]
Nope, I think 24 bit color schemes just work on vim8+ and neovim 0.1.3+. I removed that line from the `readme` because it appears to do nothing, sorry for the inconvenience

**Comment by getsadzeg** [comment]
But I almost have plaintext after opening PHP file with vim. :disappointed: Did I miss something in .vimrc?

**Comment by jacoborus** [comment]
lets see, give me more info:
- screenshot
- Exactly vim version used:
- Environment name and version (terminal, tmux, ...):
- Operating System and version:
- .vimrc file

**Comment by getsadzeg** [comment]
Here's the screenshot:

![selection_391](https://cloud.githubusercontent.com/assets/9250896/18617253/984cf74a-7ddc-11e6-9525-fe4f19c332e5.png)

Vim's version:

![selection_392](https://cloud.githubusercontent.com/assets/9250896/18617259/b1d86aa0-7ddc-11e6-8e6a-ffbc8fc0a02d.png)

I'm using [zsh](https://github.com/robbyrussell/oh-my-zsh) for my terminal.

I'm using Ubuntu 15.04

And I posted .vimrc in the description of the issue above.

**Comment by jacoborus** [comment]
does `:colors tender` return any error?

**Comment by getsadzeg** [comment]
No, but it does nothing also.

**Comment by jacoborus** [comment]
ok, that''s weird. Is that Gnome terminal? Did you try vim with other colorschemes succesfully?

**Comment by getsadzeg** [comment]
Yes, it's GNOME terminal. No I haven't tried with other colorschemes at all so far. Should I try?

**Comment by jacoborus** [comment]
yes

**Comment by jacoborus** [comment]
I just installed vim 8 in Ubuntu and made the theme work with this config:

``` viml
set nocompatible
filetype off
set termguicolors
syntax enable
colorscheme tender
```

I suppose with your vim version this should work: 

``` viml
set nocompatible
filetype off
set t_Co=256
syntax enable
colorscheme tender
```

**Comment by getsadzeg** [comment]
![selection_394](https://cloud.githubusercontent.com/assets/9250896/18618402/204ba5be-7df7-11e6-9be1-433f5d7b0940.png)

Got it, right? :+1:

**Comment by jacoborus** [comment]
Yes!! But when you update to vim8 it will look even better
