### ISSUE TITLE
Any chance of an `.Xresources` file to match?

### ISSUE THREAD

**Issue by benjumanji** [jacoborus/tender.vim#18]
I tried making on using the 16 colors listed at the bottom of the `tender.vim/colors` file but it looked awful. I would be very grateful!

**Comment by jacoborus** [comment]
Those are the main colors from the colorscheme, my Gnome Terminal looks like the screenshot below and I like it:
![selection_078](https://cloud.githubusercontent.com/assets/829859/19418306/8e76c52a-93c1-11e6-9ef5-71f4a099cfb9.png)

How does your terminal look?

**Comment by benjumanji** [comment]
Not like that! I think my problem might have been shell related (I use fish). I will play about some more and see if I can get something to work nicely for me.
