### ISSUE TITLE
tender does not work on ubuntu 

### ISSUE THREAD

**Issue by ghost** [jacoborus/tender.vim#19]
## Expected Behavior

Installed with bundle
inside vim I typed :PluginInstall
it loads all the plugins

the bug is that is doesn recognize the theme it just doesnt exists

**Comment by jacoborus** [comment]
Does the command `:colors tender` enable the colorscheme?

**Comment by ghost** [comment]
yes `:colors tender` and `:colorscheme tender` is not working it says that the scheme is missing
how can i fix that? i really like your theme

**Comment by jacoborus** [comment]
Fill the environment data of the issue template and also provide me a minimal config file (`.vimrc`) in order to reproduce your error please.

**Comment by ghost** [comment]
This is my `.vimrc` in `/home/renato`
I use zsh and vim in gnome-terminal do you think is possible zsh and vim have conflicts?
`set number` 
`set shiftwidth=4`
`set tabstop=4`
`set expandtab`
`set rtp+=~/.vim/bundle/Vundle.vim`
`call vundle#begin()`
`Plugin 'gmarik/Vundle.vim'`
`Plugin 'jacoborus/tender'`  
`syntax enable`

**Comment by jacoborus** [comment]
I use vim and neovim under gnome terminal and zsh, it looks like Vundle is not loading your plugins.

You didn't close the vundle scope in your config, you should add this after your plugin list:

``` viml
" All of your Plugins must be added before the following line 
call vundle#end() 
```

**Comment by ghost** [comment]
I forgot to put that, thanks a lot

**Comment by jacoborus** [comment]
You're welcome!
