### ISSUE TITLE
Error detected while processing .../tender-lightline.vim

### ISSUE THREAD

**Issue by blacknred0** [jacoborus/tender.vim#2]
This is my first time installing a theme for vim, and that might be my problem.  But, when I try to install it, I get the error below?  any thoughts on how to fix it?

It doesn't matter if I do it on the terminal or GUI.
Error detected while processing /home/irving/.vim/plugged/tender/plugin/tender-lightline.vim:
line   23:
E117: Unknown function: lightline#colorscheme#flatten
E15: Invalid expression: lightline#colorscheme#flatten(s:p)

**Comment by alinpopa** [comment]
Same's happening for me.

**Comment by gustavofc** [comment]
You must install https://github.com/itchyny/lightline.vim

**Comment by jacoborus** [comment]
Sorry guys, I just forgot that not everybody is using lightline. Give me 5 minutes please

**Comment by jacoborus** [comment]
@gustavofc now you must add a line to your vim config in order to enable the lightline theme:
```vim
let g:tender_lightline = 1
```

**Comment by jacoborus** [comment]
I hope this work for you, thanks for pointing it

**Comment by jacoborus** [comment]
@gustavofc  remember to add this line in order to enable the lightline theme:

``` vim
let g:tender_lightline = 1
```

**Comment by gustavofc** [comment]
Thank you!

**Comment by blacknred0** [comment]
it works now!!!  thank you!

now, according to this site -> http://vimcolors.com/436/tender/dark, it should work for both gui and terminal.  I only got it to work on my gui.  Not sure, if this needs to be updated.

**Comment by jacoborus** [comment]
@blacknred0 true color only works with gvim or neovim with `set termguicolors`. Vim on terminal should show the closest xterm colors to hex ones.
Are you getting any error or it is just different color tones?

**Comment by blacknred0** [comment]
@jacoborus I get the error below and on vim terminal, it just stayed with whatever my terminal colors are (so no color tones).
E518: Unknown option: termguicolors
Press ENTER or type command to continue

but, it seems that gvim doesn't have termguicolors in my compile version, not sure why.  it could be an error on my end.

**Comment by jacoborus** [comment]
`set termguicolors` is for neovim 0.1.5dev or newer.
What happens when you type: `:colors tender`?

**Comment by blacknred0** [comment]
When I run `:colors tender` the terminal still looks the same. :/

![screenshot](https://cloud.githubusercontent.com/assets/10933631/15321612/3a6244e6-1bfd-11e6-9c72-2a604e9b0279.png)

**Comment by jacoborus** [comment]
wow, this is really weird, I need more clues. Does your terminal support 256 colors? What terminal are you using? Did you try any other color scheme succesfully? vim version?
This could be helpful: https://gist.github.com/XVilka/8346728

**Comment by blacknred0** [comment]
aha!!! thanks for the link/inspiration.  Apparently I found through this link -> http://askubuntu.com/questions/67/how-do-i-enable-full-color-support-in-vim that I would have to override vim's autodetection and enable 256 colors for GNOME Terminal.

So, after adding this piece of code below, it looks beautiful as expected!

```
if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif
```

![screenshot-1](https://cloud.githubusercontent.com/assets/10933631/15323888/a30d662c-1c09-11e6-87c3-4ea629650386.png)

Thanks for your help

PS: I've tested this theme -> https://github.com/lifepillar/vim-wwdc16-theme and it works just fine, when I do `colorscheme wwdc16` on my `~/.vimrc` without having the need to set 256 for terminal color.

We can say this is officially closed.  Cheers!

**Comment by jacoborus** [comment]
great! but I'm pretty sure you are not having the right colors, take a look to my screenshots in the _readme_ file to see the differences.
Is your vim instance running over tmux?

**Comment by blacknred0** [comment]
you are right, I didn't noticed that.  weird :/ ... no, I am running straight from GNOME Terminal 2.31.3 on RHEL 6.7 (Santiago).

**Comment by jacoborus** [comment]
You need to know if 256 color support is enabled in Gnome Terminal, try `echo $TERM` in your terminal please, result has to be `term-256color`.
Otherwise you can set this with

``` sh
export TERM=xterm-256color
```

you can also add that line to your .bashrc

**Comment by blacknred0** [comment]
so, you were right, when I invoke that command, here is what I got

```
$ echo $TERM
xterm
```

now, I went into the terminal and did the following

```
$ export TERM=xterm-256color
$ echo $TERM              
xterm-256color
$ tput colors
256
```

I even went to the extend of setting `set t_Co=256` on `~/.vimrc` and these are the results (still same).
![screenshot-2](https://cloud.githubusercontent.com/assets/10933631/15332693/40a47e44-1c2c-11e6-9c4a-90bf6aab238c.png)

Not sure how much you want to debug this... or what else you would like me to do.

**Comment by jacoborus** [comment]
The last screenshot you posted looks ok (parens and statements in light blue and strings in light brown).
This is how a 256 color terminal should print tender color scheme:
![tender_vim_256colors](https://cloud.githubusercontent.com/assets/829859/15333256/33f82c26-1c69-11e6-9ead-a6269d9a3ff7.png)

**Comment by jacoborus** [comment]
BTW: it's 2016, I strongly recommend you to try neovim and gnome 3 :)
