### ISSUE TITLE
Errors loading tender with :colorscheme

### ISSUE THREAD

**Issue by radaniba** [jacoborus/tender.vim#21]
## Expected Behavior

Changing the vim theme using `:colorscheme` should work with no problem
## Current Behavior

When trying to load tender I have these errors : 

```
Error detected while processing ColorScheme Auto commands for "*":
E121: Undefined variable: g:colors_name
E15: Invalid expression: g:colors_name != "solarized" | silent! aunmenu Solarized | else | call SolarizedMenu() | endif
```
## Context

I am trying to get tender work with spf13-vim, which should normally work with no problems but using tender cause these errors when vim starts but the theme loads though. When trying to load tender using `:colorscheme` it fails
## My Environment
- vim (spf13-vim)
- Version used: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 14 2016 20:20:48)
- Environment name and version (terminal, tmux, ...): iTerm2
- Operating System and version: MacOS

**Comment by jacoborus** [comment]
Hi @radaniba , I believe that error is caused by Solarized theme, because that _invalid expression_ belongs to it.

Do you get this error with another theme not provided by spf13-vim?

**Comment by radaniba** [comment]
You are right, I just found the error causing the problem and commented it. vim loading fine now with no errors
Thank you

**Comment by jacoborus** [comment]
You're welcome!

**Comment by namedots** [comment]
I believe the problem is with tender.vim, I can reproduce this with:

```
$ vim -u tender.vim -c 'echo g:colors_name'
```

I believe that `g:colors_name` should be set _after_ doing `hi clear`

I encountered this problem with an autocmd in my vimrc which makes additional changes after changing colorscheme and needs to know which one is active for conditional overrides - the variable g:colors_name isn't set when using tender.vim

**Comment by jacoborus** [comment]
Ok, I believe jacoborus/estilo#30 should be merged
