### ISSUE TITLE
Tender and vim-airline-colornum incompatibilities

### ISSUE THREAD

**Issue by icaroperseo** [jacoborus/tender.vim#23]
Good day!

I am having incompatibilities with this in NeoVim 0.1.5 on Linux x64 host. Specifically, the error that appears looks like this (sorry, my system is set to Spanish language):

```
g:colors_name hi clear "ShouldUpdateCursorLineNrColor"
```

If I disable the plugin ([airline-colornum](https://github.com/ntpeters/vim-airline-colornum)) the error does not occur, although it is strange since not occur with other colorschemes, e.g. onedark.

It would be great if I could keep both enabled plugins so...

Thanks in advance!

**Comment by icaroperseo** [comment]
Well, It seems that I have found the solution to the issue (or at least it worked for me). Currently the `colors/tender.vim` file looks as follows:

```
" ===============================================================
" tender
" A dark and fresh color scheme for vim
" URL: https://github/com/jacoborus/tender.vim
" Author: Jacobo Tabernero http://jacoborus.codes
" License: MIT
" Last Change: 2016/09/25 22:42
" ===============================================================

let g:colors_name="tender"
hi clear
if exists("syntax_on")
  syntax reset
endif
set background=dark
...
```

But if the sequence of the parameters is changed the previous error does not occur:

```
" ===============================================================
" tender
" A dark and fresh color scheme for vim
" URL: https://github/com/jacoborus/tender.vim
" Author: Jacobo Tabernero http://jacoborus.codes
" License: MIT
" Last Change: 2016/09/25 22:42
" ===============================================================

set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name="tender"
...
```

I'm not a vimscript wizard but, I repeat, worked for me and I hope it will be useful to someone else.

Best regards.

**Comment by jacoborus** [comment]
Hi @icaroperseo I believe this is related to jacoborus/estilo@07155d9 . Let me know if the problem persists please
