### ISSUE TITLE
Airline tender theme is not loaded by default

### ISSUE THREAD

**Issue by icaroperseo** [jacoborus/tender.vim#25]
## Expected Behavior

The tender theme for airline should be loaded whithout issues in establishing the following Inside the _init.vim_ file:

```
colorscheme tender
let g:airline_theme = 'tender'
```

## Current Behavior

When I attempting to load this theme I get the following error message: `Could not resolve airline theme "tender". Themes have been migrated to github.com/vim-ariline/vim-ariline-themes.`. Because of this, the airline default theme is loaded instead.

## Context

Before [this](https://github.com/jacoborus/tender.vim/commit/b902131740ff19d85bb7d13056657fcbff18057b) commit, the tender theme was loaded without any problem by airline through **vim-plug**.

## My Environment
* vim, neovim, gVim, MacVim, ...?: _NeoVim_
* Version used: _0.1.6_
* Environment name and version (terminal, tmux, ...): _Konsole/Sakura terminal + Tmux_
* Operating System and version: _GNU/Linux x86_64_

**Comment by jacoborus** [comment]
I am on the same environment you are working with v0.2.0 but I cannot reproduce your error. Could you try with @noharp version (https://github.com/noharp/tender.vim) and let me know if that fixes the error please?

**Comment by icaroperseo** [comment]
Hi!

I tried what you suggested to me but I was not lucky, The error message still continues to appear and the airline theme is not loaded.

**Comment by taq** [comment]
Would be a good idea to port the airline theme to the repo where all the other themes are now: https://github.com/vim-airline/vim-airline-themes

**Comment by aar0nTw** [comment]
I have same problem on NeoVim latest version, and I try to update 

https://github.com/jacoborus/tender.vim/blob/master/autoload/airline/themes/tender.vim#L40-L42

```vim
let s:CP1 = [ "", "", ,  ]
let s:CP2 = [ "", "", ,  ]
let s:CP3 = [ "", "", ,  ]
```

to 

```vim
let s:CP1 = [ "", "", 0, 0]
let s:CP2 = [ "", "", 0, 0]
let s:CP3 = [ "", "", 0, 0]
```

And It works.

**Comment by icaroperseo** [comment]
@aar0nTw It works like a charm!

**Comment by jacoborus** [comment]
Thanks @aar0nTw ! I will fix [Estilo](https://github.com/jacoborus/estilo) and [Tender](https://github.com/jacoborus/tender.vim) tonight
