### ISSUE TITLE
Param Colors?

### ISSUE THREAD

**Issue by hlwrocer** [jacoborus/tender.vim#30]
## Expected Behavior
Achieving the same colors provided in the screenshtos

## Current Behavior
Was wondering if you needed to do something to achieve the colors, specifically for the parameters
![image](https://user-images.githubusercontent.com/8906127/27246611-ae557080-52c0-11e7-8c81-0e2503b6bc24.png)

## My Environment
vim 8.0
tmux on bash on windows

**Comment by michael-a-grammar** [comment]
@hlwrocer Try installing https://github.com/othree/yajs.vim
