### ISSUE TITLE
gnome-terminal colors

### ISSUE THREAD

**Issue by verdie-g** [jacoborus/tender.vim#34]
Hi,

I'm trying to create a gnome-terminal profile with tender's colors taken from the [palette image](https://cloud.githubusercontent.com/assets/829859/18413534/f7cb472c-77aa-11e6-86bf-9c790aadd2df.png) and [palettes/tender.yml](https://github.com/jacoborus/tender.vim/blob/master/estilo/palettes/tender.yml).

Here's what I got:

![2018-04-02-185816_569x377_scrot](https://user-images.githubusercontent.com/9092290/38205714-d72e38f4-36a7-11e8-8535-d13d97ef20c3.png)

However, I don't know which color to use for the 6th and 7th columns. What would you use ?

**Comment by vaga** [comment]
You can use colors defined at the end of `colors/tender.vim`
https://github.com/jacoborus/tender.vim/blob/master/colors/tender.vim#L227

**Comment by jacoborus** [comment]
![tender-terminal](https://user-images.githubusercontent.com/829859/46538590-b029d480-c8b4-11e8-8a59-629ddca09c86.png)

I'm using this config: 
- #2E3436 / #555753
- #F43753
- #C9D05C
- #FFC24B
- #73CEF4
- #B3DEEF
- #D3B987
- #D3D7CF / #EEEEEC
