### ISSUE TITLE
How to change selection color?

### ISSUE THREAD

**Issue by idankor** [jacoborus/tender.vim#40]
## My Environment
* vim, neovim, gVim, MacVim, ...?:
* Version used:
* Environment name and version (terminal, tmux, ...):
* Operating System and version:

**Comment by kazhala** [comment]
<img width="821" alt="Screen Shot 2019-11-07 at 16 38 50" src="https://user-images.githubusercontent.com/43941510/68362928-2d411080-017d-11ea-98de-657267d29b05.png">
If this is what you meant. Default selection is a bit hard to see for me

**Comment by jacoborus** [comment]
I just changed the colors in visual mode
