### ISSUE TITLE
Floating window colors are hard to read

### ISSUE THREAD

**Issue by cdimitroulas** [jacoborus/tender.vim#41]
## Expected Behavior
Floating window should be readable

## Current Behavior
Not readable

## Context
![image](https://user-images.githubusercontent.com/20640274/68380420-b4739180-0147-11ea-8f6b-9e9742752d4a.png)

## My Environment
* vim, neovim, gVim, MacVim, ...?: neovim 0.4.2
* Version used: 0.4.2
* Environment name and version (terminal, tmux, ...): tmux 2.6
* Operating System and version: Ubuntu 18.04

**Comment by juliandkatz** [comment]
I'm having the same problem.  In particular, the type information of parameters with primitive types lacks sufficient contrast to be readable.  (The example below includes the parameter `fileName` of type `string`.

<img width="510" alt="Screen Shot 2020-01-13 at 7 14 00 PM" src="https://user-images.githubusercontent.com/8396513/72311271-eff37600-3638-11ea-92e2-7557bf7aebd2.png">

I'm coding in golang, using [coc.nvim](https://github.com/neoclide/coc.nvim) as my autocompletion engine.

## My Environment

- neovim
- v0.4.3
- tmux 2.7
- MacOS Mojave (10.14.6)

**Comment by jacoborus** [comment]
![pmenu](https://user-images.githubusercontent.com/829859/74184515-368fbc80-4c47-11ea-848c-09bc28960b56.png)
