### ISSUE TITLE
line highlighting in vimoutliner changes only every 2nd 

### ISSUE THREAD

**Issue by nilsbecker** [jacoborus/tender.vim#43]
## Expected Behavior

in a vimoutliner file, line color changes every level of indentation

## Current Behavior

it changes only every 2 levels

## Context

see here: 

https://github.com/vimoutliner/vimoutliner/issues/166

## My Environment
* MacVim current

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
macOS version
Included patches: 1-2234

**Comment by jacoborus** [comment]
I can't fix that because it will break a lot of the syntax highlighting. Maybe you can try changing the color of the statements when you are using the plugin
```
hi Statement guifg=#f43753 ctermfg=153 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE
```
