### ISSUE TITLE
Odd highlights in floating window (NeoVim + CoC)

### ISSUE THREAD

**Issue by gvolpe** [jacoborus/tender.vim#44]
Hi,

I was wondering if you could help me figure out how to solve this issue that seems to be CoC's fault but that there are [workarounds suggested](https://github.com/neoclide/coc.nvim/wiki/F.A.Q#highlight-of-background-seems-wrong-with-floating-window) by its author.

[Here](https://github.com/joshdick/onedark.vim/issues/197) is a detailed report of the issue and how it was possible to fix it for the OneDark theme.

[Here](https://github.com/neoclide/coc.nvim/issues/1248) is the associated issue reported in CoC.

I looked into the colors defined by Tender and tried some configurations without any luck.

## My Environment

* NeoVim v0.4.3
* Environment name and version (terminal, tmux, ...): N/A
* Operating System and version: N/A

Appreciate any help and thanks for creating this awesome theme! :heart_eyes:

**Comment by jacoborus** [comment]
@gvolpe I made some changes that should fix it. If the issue persists please reopen

**Comment by gvolpe** [comment]
Thanks a lot @jacoborus , it seems to work! :tada:
