### ISSUE TITLE
Doesn't have any separation/vertical bar for vertical windows

### ISSUE THREAD

**Issue by nikhilvijayanv** [jacoborus/tender.vim#48]
## Current Behavior
Code of both vertical windows looks like they are from same window as there is no separator

## Context
Just do a vsplit in neovim

## My Environment
* vim, neovim, gVim, MacVim, ...?: Neovim
* Version used: NVIM v0.4.4
* Environment name and version (terminal, tmux, ...):  Neovim-Qt, Terminal
* Operating System and version: Debian 10

**Comment by jacoborus** [comment]
That's intentional. You can add this line to your `.vimrc` file to make them visible:

```vim
hi VertSplit guifg=#111111 ctermfg=233 guibg=#111111 ctermbg=233 gui=NONE cterm=NONE
```
