### ISSUE TITLE
Two more terminal themes

### ISSUE THREAD

**Issue by Rafaelcv7** [jacoborus/tender.vim#49]
Hey i like your Tender theme so i made two file adaptation for use in Blink Shell ios app
and also in Windows Terminal app.

You can see them here, and add them if you like.
https://github.com/Rafaelcv7/Jacoborus-Tendertheme

**Comment by jacoborus** [comment]
Thanks, I just linked it in the README 7746453a045eaa97dc413a7209268345f33f3243
