### ISSUE TITLE
Neovim true color support

### ISSUE THREAD

**Issue by mklein994** [jacoborus/tender.vim#5]
Neovim has a setting [`'termguicolors'`](https://github.com/neovim/neovim/wiki/FAQ#how-can-i-use-true-colors-in-the-terminal) that allows true color schemes (like the gui) in the terminal, if the terminal supports 24-bit color (see this [gist](https://gist.github.com/XVilka/8346728) for supported terminals). It would be great if tender could support this.

**Comment by jacoborus** [comment]
Hi @mklein994 , tender is already using true color in neovim when `set termguicolors`.
What do you see when you use this option, 256 color fallback or just weird colors?

**Comment by mklein994** [comment]
Sorry; that was my fault. I had these lines scattered in the following order in my `init.vim`:

``` vim
set termguicolors
colorscheme tender
syntax on " This line reset the colors on me to the defaults.
```

All fixed now.
