### ISSUE TITLE
Any easy way to port to vscode?

### ISSUE THREAD

**Issue by jmreicha** [jacoborus/tender.vim#52]
I am really enjoying this theme so far, I have it working across a number of environments. I was wondering if there is any tool to use or easy way to get the theme ported over vscode?

**Comment by jmreicha** [comment]
I ended up making my own if anyone is interested https://github.com/jmreicha/tender-vscode. Still needs some work but is mostly working.

**Comment by jacoborus** [comment]
Unfortunately, I don't know any easy way to port it to VSCode. How is it doing your implementation so far?

**Comment by jmreicha** [comment]
I basically just used the color pallet as a base and added some extra customizations.
