### ISSUE TITLE
Parsing errors on neovim

### ISSUE THREAD

**Issue by cujomalainey** [jacoborus/tender.vim#60]
## Expected Behavior
No errors on startup

## Current Behavior
```
Error detected while processing /usr/local/google/home/cujomalainey/.local/share/nvim/plugged/tender.vim/colors/tender.vim:                                  
line  277:                                                                                                                                                   
W18: Invalid character in group name                                                                                                                         
line  278:                                                                                                                                                   
W18: Invalid character in group name                                                                                                                         
line  279:                                                                                                                                                   
W18: Invalid character in group name 
```
Bug introduced in this commit https://github.com/jacoborus/tender.vim/commit/35fcab45f752776c914225c1da6123ee7572998f

I can check out it's parent and it works fine

## Context
Annoying spam on editor open

## My Environment
* vim, neovim, gVim, MacVim, ...?: neovim
* Version used: NVIM v0.7.2
* Environment name and version (terminal, tmux, ...): terminator
* Operating System and version: debian

**Comment by cujomalainey** [comment]
Wouldn't be surprised if this is simply debian being so far behind that this is a syntax unknown to the editor

**Comment by jacoborus** [comment]
Thanks for reporting @cujomalainey . It's not a Debian problem, it's a problem in the colorscheme generator [estilo](https://github.com/jacoborus/estilo). I thought the `@` prefix was part of the Neovim syntax, but it depends on some plugins: [lsp-config](https://github.com/neovim/nvim-lspconfig) and [tree-sitter](https://github.com/nvim-treesitter/nvim-treesitter). I'm trying to figure out how to incorporate them into [estilo](https://github.com/jacoborus/estilo) without adding breaking changes

**Comment by jacoborus** [comment]
I just added a temporary fix to this repo, hope it works

**Comment by cujomalainey** [comment]
> I just added a temporary fix to this repo, hope it works

Just pulled down on my macbook, seems to work, will test the debian machine later today :)

**Comment by cujomalainey** [comment]
> > I just added a temporary fix to this repo, hope it works
> 
> Just pulled down on my macbook, seems to work, will test the debian machine later today :)

Debian also validated, thanks for the quick fix
