### ISSUE TITLE
MacVim Colorscheme fails to load

### ISSUE THREAD

**Issue by tombell** [jacoborus/tender.vim#9]
I am trying to use tender in MacVim, I've set `colorscheme tender` in my `.vimrc`, however when opening MacVim the color scheme isn't applied, however when do the command `:colorscheme tender` it works fine.

**Comment by jacoborus** [comment]
It looks like something is overwriting the  colorscheme or the color config. Moving the `:colorscheme tender` line to the bottom of the `.vimrc` does help?

**Comment by tombell** [comment]
I tried that and it still fails to load. This is the only color scheme I've found where this happens.

**Comment by tombell** [comment]
I managed to fix this by setting `let macvim_skip_colorscheme=1` in `.vimrc`.

**Comment by jacoborus** [comment]
Nice! I will add that line to the readme file

**Comment by tombell** [comment]
It seemed to be loading the colorscheme from `gvimrc` which I don't use, but creating a `.gvimrc` with the colorscheme in worked. Don't know why it was only with this color scheme. Either way love this color scheme :)

**Comment by jacoborus** [comment]
Hey @tombell , can you update tender, try again without the `let macvim_skip_colorscheme=1` and tell if it works well now please?

**Comment by tombell** [comment]
Same issue as before I'm afraid.

**Comment by jithine** [comment]
I have the same issue, however adding `let macvim_skip_colorscheme=1` fixes it.
